PROJNAME=Thesis_Revolute
DEVICE=CY8C28433
BASEDEVICE=CY8C28033
PROJPATH=C:/Users/Admin/DOCUME~1/PSOCDE~1.0PR/THESIS~2/THESIS~1
PSOCDIR=C:/PROGRA~1/Cypress/Common/CYPRES~3
INCLUDE_PATH=C:/PROGRA~1/Cypress/Common/CYPRES~3/tools/include/CY60D2~1
CSRCS= main.c
LIBCSRCS=
ASMSRCS=
LIBASMSRCS= child_1.asm child_1_timeout.asm child_1_timeoutint.asm child_1int.asm child_1plus.asm child_2.asm child_2_timeout.asm child_2_timeoutint.asm child_2int.asm child_2plus.asm child_3.asm child_3_timeout.asm child_3_timeoutint.asm child_3int.asm child_3plus.asm child_4.asm child_4_timeout.asm child_4_timeoutint.asm child_4int.asm child_4plus.asm hello_1.asm hello_1int.asm hello_1plus.asm hello_2.asm hello_2int.asm hello_2plus.asm hello_3.asm hello_3int.asm hello_3plus.asm hello_4.asm hello_4int.asm hello_4plus.asm hello_timeout.asm hello_timeoutint.asm init_rx.asm init_rxint.asm init_rxplus.asm init_timeout.asm init_timeoutint.asm psocconfig.asm psocconfigtbl.asm psocdynamic.asm psocdynamicint.asm rx8_2.asm rx8_2int.asm rx8_2plus.asm servo_tx.asm servo_txint.asm servo_txplus.asm tx_01234_timeout.asm tx_01234_timeoutint.asm tx_014.asm tx_014int.asm tx_014plus.asm tx_23.asm tx_23int.asm tx_23plus.asm wait_recv.asm wait_recvint.asm wait_recvplus.asm
OBJECT_SOURCES= main.c
FILLVALUE=0x30
LASTROM=0x3fff
LASTRAM=0x3ff
LAST_DATARAM=0x2ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-nomac -Wf-Osize -Wf-LMM4 -D_LMM
RELSTART=0x190
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_3 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=thesis_revolute waiting hello initial my_response response1 response2 response3 response4 servo_transmit waiting hello initial my_response response1 response2 response3 response4 servo_transmit waiting hello initial my_response response1 response2 response3 response4 servo_transmit waiting hello initial my_response response1 response2 response3 response4 servo_transmit waiting hello initial my_response response1 response2 response3 response4 servo_transmit waiting hello initial my_response response1 response2 response3 response4 servo_transmit waiting hello initial my_response response1 response2 response3 response4 servo_transmit waiting hello initial my_response response1 response2 response3 response4 servo_transmit waiting hello initial my_response response1 response2 response3 response4 servo_transmit 
