//*****************************************************************************
//*****************************************************************************
//  FILENAME: INIT_TIMEOUT.h
//   Version: 2.6, Updated on 2009/7/10 at 10:46:29
//  Generated by PSoC Designer 5.0.985.0
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//               for the 22/24/27/29xxx PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2000-2004. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 INIT_TIMEOUT_EnableInt
#pragma fastcall16 INIT_TIMEOUT_DisableInt
#pragma fastcall16 INIT_TIMEOUT_Start
#pragma fastcall16 INIT_TIMEOUT_Stop
#pragma fastcall16 INIT_TIMEOUT_wReadTimer                // Read  DR0
#pragma fastcall16 INIT_TIMEOUT_wReadTimerSaveCV          // Read  DR0      
#pragma fastcall16 INIT_TIMEOUT_WritePeriod               // Write DR1
#pragma fastcall16 INIT_TIMEOUT_wReadCompareValue         // Read  DR2
#pragma fastcall16 INIT_TIMEOUT_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wINIT_TIMEOUT_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 wINIT_TIMEOUT_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 wINIT_TIMEOUT_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 wINIT_TIMEOUT_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 wINIT_TIMEOUT_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the INIT_TIMEOUT API.
//-------------------------------------------------

extern void INIT_TIMEOUT_EnableInt(void);                           // Proxy 1
extern void INIT_TIMEOUT_DisableInt(void);                          // Proxy 1
extern void INIT_TIMEOUT_Start(void);                               // Proxy 1
extern void INIT_TIMEOUT_Stop(void);                                // Proxy 1
extern WORD INIT_TIMEOUT_wReadTimer(void);                          // Proxy 1
extern WORD INIT_TIMEOUT_wReadTimerSaveCV(void);                    // Proxy 2
extern void INIT_TIMEOUT_WritePeriod(WORD wPeriod);                 // Proxy 1
extern WORD INIT_TIMEOUT_wReadCompareValue(void);                   // Proxy 1
extern void INIT_TIMEOUT_WriteCompareValue(WORD wCompareValue);     // Proxy 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wINIT_TIMEOUT_ReadCompareValue(void);       // Deprecated
extern WORD wINIT_TIMEOUT_ReadTimerSaveCV(void);        // Deprecated
extern WORD wINIT_TIMEOUT_ReadCounter(void);            // Obsolete
extern WORD wINIT_TIMEOUT_ReadTimer(void);              // Deprecated
extern WORD wINIT_TIMEOUT_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for INIT_TIMEOUT API's.
//--------------------------------------------------

#define INIT_TIMEOUT_CONTROL_REG_START_BIT     ( 0x01 )
#define INIT_TIMEOUT_INT_REG_ADDR              ( 0x0e1 )
#define INIT_TIMEOUT_INT_MASK                  ( 0x02 )


//--------------------------------------------------
// Constants for INIT_TIMEOUT user defined values
//--------------------------------------------------

#define INIT_TIMEOUT_PERIOD                    ( 0x1e0 )
#define INIT_TIMEOUT_COMPARE_VALUE             ( 0x0 )


//-------------------------------------------------
// Register Addresses for INIT_TIMEOUT
//-------------------------------------------------

#pragma ioport  INIT_TIMEOUT_COUNTER_LSB_REG:   0x020      //Count register LSB
BYTE            INIT_TIMEOUT_COUNTER_LSB_REG;
#pragma ioport  INIT_TIMEOUT_COUNTER_MSB_REG:   0x024      //Count register MSB
BYTE            INIT_TIMEOUT_COUNTER_MSB_REG;
#pragma ioport  INIT_TIMEOUT_PERIOD_LSB_REG:    0x021      //Period register LSB
BYTE            INIT_TIMEOUT_PERIOD_LSB_REG;
#pragma ioport  INIT_TIMEOUT_PERIOD_MSB_REG:    0x025      //Period register MSB
BYTE            INIT_TIMEOUT_PERIOD_MSB_REG;
#pragma ioport  INIT_TIMEOUT_COMPARE_LSB_REG:   0x022      //Compare register LSB
BYTE            INIT_TIMEOUT_COMPARE_LSB_REG;
#pragma ioport  INIT_TIMEOUT_COMPARE_MSB_REG:   0x026      //Compare register MSB
BYTE            INIT_TIMEOUT_COMPARE_MSB_REG;
#pragma ioport  INIT_TIMEOUT_CONTROL_LSB_REG:   0x023      //Control register LSB
BYTE            INIT_TIMEOUT_CONTROL_LSB_REG;
#pragma ioport  INIT_TIMEOUT_CONTROL_MSB_REG:   0x027      //Control register MSB
BYTE            INIT_TIMEOUT_CONTROL_MSB_REG;
#pragma ioport  INIT_TIMEOUT_FUNC_LSB_REG:  0x120          //Function register LSB
BYTE            INIT_TIMEOUT_FUNC_LSB_REG;
#pragma ioport  INIT_TIMEOUT_FUNC_MSB_REG:  0x124          //Function register MSB
BYTE            INIT_TIMEOUT_FUNC_MSB_REG;
#pragma ioport  INIT_TIMEOUT_INPUT_LSB_REG: 0x121          //Input register LSB
BYTE            INIT_TIMEOUT_INPUT_LSB_REG;
#pragma ioport  INIT_TIMEOUT_INPUT_MSB_REG: 0x125          //Input register MSB
BYTE            INIT_TIMEOUT_INPUT_MSB_REG;
#pragma ioport  INIT_TIMEOUT_OUTPUT_LSB_REG:    0x122      //Output register LSB
BYTE            INIT_TIMEOUT_OUTPUT_LSB_REG;
#pragma ioport  INIT_TIMEOUT_OUTPUT_MSB_REG:    0x126      //Output register MSB
BYTE            INIT_TIMEOUT_OUTPUT_MSB_REG;
#pragma ioport  INIT_TIMEOUT_INT_REG:       0x0e1          //Interrupt Mask Register
BYTE            INIT_TIMEOUT_INT_REG;


//-------------------------------------------------
// INIT_TIMEOUT Macro 'Functions'
//-------------------------------------------------

#define INIT_TIMEOUT_Start_M \
   ( INIT_TIMEOUT_CONTROL_LSB_REG |=  INIT_TIMEOUT_CONTROL_REG_START_BIT )

#define INIT_TIMEOUT_Stop_M  \
   ( INIT_TIMEOUT_CONTROL_LSB_REG &= ~INIT_TIMEOUT_CONTROL_REG_START_BIT )

#define INIT_TIMEOUT_EnableInt_M   \
   M8C_EnableIntMask(  INIT_TIMEOUT_INT_REG, INIT_TIMEOUT_INT_MASK )

#define INIT_TIMEOUT_DisableInt_M  \
   M8C_DisableIntMask( INIT_TIMEOUT_INT_REG, INIT_TIMEOUT_INT_MASK )


// end of file INIT_TIMEOUT.h


