/******************************************************************************
*  Generated by PSoC Designer 5.0.985.0
******************************************************************************/
extern void LoadConfig_waiting( void);
extern void ReloadConfig_waiting( void);
extern void UnloadConfig_waiting( void);
extern char IswaitingLoaded( void);
extern void LoadConfig_hello( void);
extern void UnloadConfig_hello( void);
extern char IshelloLoaded( void);
extern void LoadConfig_initial( void);
extern void UnloadConfig_initial( void);
extern char IsinitialLoaded( void);
extern void LoadConfig_my_response( void);
extern void UnloadConfig_my_response( void);
extern char Ismy_responseLoaded( void);
extern void LoadConfig_response1( void);
extern void UnloadConfig_response1( void);
extern char Isresponse1Loaded( void);
extern void LoadConfig_response2( void);
extern void UnloadConfig_response2( void);
extern char Isresponse2Loaded( void);
extern void LoadConfig_response3( void);
extern void UnloadConfig_response3( void);
extern char Isresponse3Loaded( void);
extern void LoadConfig_response4( void);
extern void UnloadConfig_response4( void);
extern char Isresponse4Loaded( void);
extern void LoadConfig_servo_transmit( void);
extern void UnloadConfig_servo_transmit( void);
extern char Isservo_transmitLoaded( void);
extern void UnloadConfig_Total( void);
