//*****************************************************************************
//*****************************************************************************
//  FILENAME: SERVO_TX.h
//   Version: 3.3, Updated on 2009/7/10 at 10:46:51
//  Generated by PSoC Designer 5.0.985.0
//
//  DESCRIPTION: TX8 User Module C Language interface file for the
//               22/24/25/26/27xxx PSoC family of devices.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  SERVO_TX_SetTxIntMode
#pragma fastcall16  SERVO_TX_EnableInt
#pragma fastcall16  SERVO_TX_DisableInt
#pragma fastcall16  SERVO_TX_Start
#pragma fastcall16  SERVO_TX_Stop
#pragma fastcall16  SERVO_TX_SendData
#pragma fastcall16  SERVO_TX_bReadTxStatus

// High level TX functions
#pragma fastcall16  SERVO_TX_PutSHexByte
#pragma fastcall16  SERVO_TX_PutSHexInt
#pragma fastcall16  SERVO_TX_CPutString
#pragma fastcall16  SERVO_TX_PutString
#pragma fastcall16  SERVO_TX_PutChar
#pragma fastcall16  SERVO_TX_Write
#pragma fastcall16  SERVO_TX_CWrite
#pragma fastcall16  SERVO_TX_PutCRLF

//-------------------------------------------------
// Prototypes of the SERVO_TX API.
//-------------------------------------------------
extern void  SERVO_TX_SetTxIntMode(BYTE bTxIntMode);
extern void  SERVO_TX_EnableInt(void);
extern void  SERVO_TX_DisableInt(void);
extern void  SERVO_TX_Start(BYTE bParity);
extern void  SERVO_TX_Stop(void);
extern void  SERVO_TX_SendData(BYTE bTxData);
extern BYTE  SERVO_TX_bReadTxStatus(void);

// High level TX functions
extern void   SERVO_TX_CPutString(const char * szRomString);
extern void   SERVO_TX_PutString(char * szRamString);
extern void   SERVO_TX_PutChar(CHAR cData);
extern void   SERVO_TX_Write(char * szRamString, BYTE bCount);
extern void   SERVO_TX_CWrite(const char * szRomString, INT iCount);
extern void   SERVO_TX_PutSHexByte(BYTE bValue);
extern void   SERVO_TX_PutSHexInt(INT iValue);
extern void   SERVO_TX_PutCRLF(void);

// Old style function name, Do Not Use.
// Will be removfr in a future release
#pragma fastcall16 bSERVO_TX_ReadTxStatus
extern BYTE bSERVO_TX_ReadTxStatus(void);

//------------------------------------
//  Transmitter Parity masks
//------------------------------------
#define  SERVO_TX_PARITY_NONE         0x00
#define  SERVO_TX_PARITY_EVEN         0x02
#define  SERVO_TX_PARITY_ODD          0x06

//------------------------------------
//  Transmitter Status Register masks
//------------------------------------
#define  SERVO_TX_TX_COMPLETE         0x20
#define  SERVO_TX_TX_BUFFER_EMPTY     0x10

#define SERVO_TX_INT_MODE_TX_REG_EMPTY 0x00
#define SERVO_TX_INT_MODE_TX_COMPLETE  0x01

//------------------------------------
// Transmitter Interrupt masks
//------------------------------------
#define SERVO_TX_INT_REG_ADDR                  ( 0x0e1 )
#define SERVO_TX_bINT_MASK                     ( 0x04 )

// Old style defines, do not use.  These
// will be removed in a future release.
#define  TX8_PARITY_NONE         0x00
#define  TX8_PARITY_EVEN         0x02
#define  TX8_PARITY_ODD          0x06
#define  TX8_TX_COMPLETE         0x20
#define  TX8_TX_BUFFER_EMPTY     0x10



//-------------------------------------------------
// Register Addresses for SERVO_TX
//-------------------------------------------------
#pragma ioport  SERVO_TX_CONTROL_REG:   0x02b              // Control register
BYTE            SERVO_TX_CONTROL_REG;
#pragma ioport  SERVO_TX_TX_SHIFT_REG:  0x028              // TX Shift Register register
BYTE            SERVO_TX_TX_SHIFT_REG;
#pragma ioport  SERVO_TX_TX_BUFFER_REG: 0x029              // TX Buffer Register
BYTE            SERVO_TX_TX_BUFFER_REG;
#pragma ioport  SERVO_TX_FUNC_REG:  0x128                  // Function register
BYTE            SERVO_TX_FUNC_REG;
#pragma ioport  SERVO_TX_INPUT_REG: 0x129                  // Input register
BYTE            SERVO_TX_INPUT_REG;
#pragma ioport  SERVO_TX_OUTPUT_REG:    0x12a              // Output register
BYTE            SERVO_TX_OUTPUT_REG;

// end of file SERVO_TX.h
