//*****************************************************************************
//*****************************************************************************
//  FILENAME: WAIT_RECV.h
//   Version: 3.3, Updated on 2009/7/10 at 10:46:15
//  Generated by PSoC Designer 5.0.985.0
//
//  DESCRIPTION:  RX8 User Module C Language interface file for the
//                22/24/25/26/27xxx PSoC family of devices.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************


// include the global header file
#include <m8c.h>

#define WAIT_RECV_RXBUF_ENABLE 1

//-------------------------------------------------
// Prototypes of the WAIT_RECV API.
//-------------------------------------------------

#if ( WAIT_RECV_RXBUF_ENABLE )
extern char WAIT_RECV_aRxBuffer[];
extern BYTE WAIT_RECV_bRxCnt;
extern BYTE WAIT_RECV_fStatus;
#endif

// Create pragmas to support proper argument and return value passing
#pragma fastcall16  WAIT_RECV_EnableInt
#pragma fastcall16  WAIT_RECV_DisableInt
#pragma fastcall16  WAIT_RECV_Start
#pragma fastcall16  WAIT_RECV_Stop
#pragma fastcall16  WAIT_RECV_bReadRxData
#pragma fastcall16  WAIT_RECV_bReadRxStatus

#pragma fastcall16  WAIT_RECV_cGetChar
#pragma fastcall16  WAIT_RECV_cReadChar
#pragma fastcall16  WAIT_RECV_iReadChar

#if ( WAIT_RECV_RXBUF_ENABLE )
#pragma fastcall16  WAIT_RECV_CmdReset
#pragma fastcall16  WAIT_RECV_bCmdCheck
#pragma fastcall16  WAIT_RECV_bErrCheck
#pragma fastcall16  WAIT_RECV_bCmdLength
#pragma fastcall16  WAIT_RECV_szGetParam
#pragma fastcall16  WAIT_RECV_szGetRestOfParams
#endif

//-------------------------------------------------
// Prototypes of the WAIT_RECV API.
//-------------------------------------------------
extern void  WAIT_RECV_EnableInt(void);
extern void  WAIT_RECV_DisableInt(void);
extern void  WAIT_RECV_Start(BYTE bParity);
extern void  WAIT_RECV_Stop(void);
extern BYTE  WAIT_RECV_bReadRxData(void);
extern BYTE  WAIT_RECV_bReadRxStatus(void);

// High level RX functions
extern CHAR         WAIT_RECV_cGetChar(void);
extern CHAR         WAIT_RECV_cReadChar(void);
extern INT          WAIT_RECV_iReadChar(void);

#if ( WAIT_RECV_RXBUF_ENABLE )
extern void   WAIT_RECV_CmdReset(void);
extern BYTE   WAIT_RECV_bCmdCheck(void);
extern BYTE   WAIT_RECV_bErrCheck(void);
extern BYTE   WAIT_RECV_bCmdLength(void);
extern char * WAIT_RECV_szGetParam(void);
extern char * WAIT_RECV_szGetRestOfParams(void);
#endif

// Old function call names, do not use.
// These names will be removed in a future release.
#pragma fastcall16 bWAIT_RECV_ReadRxData
#pragma fastcall16 bWAIT_RECV_ReadRxStatus
extern BYTE bWAIT_RECV_ReadRxData(void);
extern BYTE bWAIT_RECV_ReadRxStatus(void);

//-------------------------------------------------
// Constants for WAIT_RECV API's.
//-------------------------------------------------

//------------------------------------
// Receiver Interrupt masks
//------------------------------------
#define WAIT_RECV_INT_REG_ADDR                 ( 0x0e1 )
#define WAIT_RECV_bINT_MASK                    ( 0x04 )

//------------------------------------
// Receiver Parity masks
//------------------------------------
#define  WAIT_RECV_PARITY_NONE         0x00
#define  WAIT_RECV_PARITY_EVEN         0x02
#define  WAIT_RECV_PARITY_ODD          0x06

//------------------------------------
//  Receiver Status Register masks
//------------------------------------
#define  WAIT_RECV_RX_ACTIVE           0x10
#define  WAIT_RECV_RX_COMPLETE         0x08
#define  WAIT_RECV_RX_PARITY_ERROR     0x80
#define  WAIT_RECV_RX_OVERRUN_ERROR    0x40
#define  WAIT_RECV_RX_FRAMING_ERROR    0x20
#define  WAIT_RECV_RX_NO_ERROR         0xE0

#define  WAIT_RECV_RX_NO_DATA         0x01

#define  WAIT_RECV_RX_BUF_ERROR           0xF0  // Mask for any Rx that may occur.
#define  WAIT_RECV_RX_BUF_OVERRUN         0x10  // This indicates the software buffer has
                                                           // been over run.
#define  WAIT_RECV_RX_BUF_CMDTERM         0x01  // Command terminator has been received.

// Old defines, will be removed in future release
#define  RX8_PARITY_NONE         0x00
#define  RX8_PARITY_EVEN         0x02
#define  RX8_PARITY_ODD          0x06
#define  RX8_RX_ACTIVE           0x10
#define  RX8_RX_COMPLETE         0x08
#define  RX8_RX_PARITY_ERROR     0x80
#define  RX8_RX_OVERRUN_ERROR    0x40
#define  RX8_RX_FRAMING_ERROR    0x20
#define  RX8_RX_NO_ERROR         0xE0

//-------------------------------------------------
// Register Addresses for WAIT_RECV
//-------------------------------------------------
#pragma ioport  WAIT_RECV_CONTROL_REG:  0x02b              // Control register
BYTE            WAIT_RECV_CONTROL_REG;
#pragma ioport  WAIT_RECV_RX_SHIFT_REG: 0x028              // RX Shift Register register
BYTE            WAIT_RECV_RX_SHIFT_REG;
#pragma ioport  WAIT_RECV_RX_BUFFER_REG:    0x02a              // RX Buffer Register
BYTE            WAIT_RECV_RX_BUFFER_REG;
#pragma ioport  WAIT_RECV_FUNC_REG: 0x128                  // Function register
BYTE            WAIT_RECV_FUNC_REG;
#pragma ioport  WAIT_RECV_INPUT_REG:    0x129              // Input register
BYTE            WAIT_RECV_INPUT_REG;
#pragma ioport  WAIT_RECV_OUTPUT_REG:   0x12a              // Output register
BYTE            WAIT_RECV_OUTPUT_REG;

// end of file WAIT_RECV.h

