; Generated by PSoC Designer 5.0.985.0
;
;
;  thesis_revoluteDynamic.asm
;
;  Data: 11 June, 2004
;  Copyright Cypress MicroSystems 2001-2004
;
;  This file is generated by the Device Editor on Application Generation.
;  It contains functions that can be used to test the state of the 
;  currently active configuration.
;  
;  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
;  Edits to this file will not be preserved.
;
include "m8c.inc"
include "memory.inc"
include "PSoCDynamic.inc"
export IswaitingLoaded
export _IswaitingLoaded
export IshelloLoaded
export _IshelloLoaded
export IsinitialLoaded
export _IsinitialLoaded
export Ismy_responseLoaded
export _Ismy_responseLoaded
export Isresponse1Loaded
export _Isresponse1Loaded
export Isresponse2Loaded
export _Isresponse2Loaded
export Isresponse3Loaded
export _Isresponse3Loaded
export Isresponse4Loaded
export _Isresponse4Loaded
export Isservo_transmitLoaded
export _Isservo_transmitLoaded
IswaitingLoaded:
_IswaitingLoaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+waiting_ADDR_OFF], waiting_BIT
	jz		waitingIsNotLoaded
	mov		a, 1
waitingIsNotLoaded:
	ret

IshelloLoaded:
_IshelloLoaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+hello_ADDR_OFF], hello_BIT
	jz		helloIsNotLoaded
	mov		a, 1
helloIsNotLoaded:
	ret

IsinitialLoaded:
_IsinitialLoaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+initial_ADDR_OFF], initial_BIT
	jz		initialIsNotLoaded
	mov		a, 1
initialIsNotLoaded:
	ret

Ismy_responseLoaded:
_Ismy_responseLoaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+my_response_ADDR_OFF], my_response_BIT
	jz		my_responseIsNotLoaded
	mov		a, 1
my_responseIsNotLoaded:
	ret

Isresponse1Loaded:
_Isresponse1Loaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+response1_ADDR_OFF], response1_BIT
	jz		response1IsNotLoaded
	mov		a, 1
response1IsNotLoaded:
	ret

Isresponse2Loaded:
_Isresponse2Loaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+response2_ADDR_OFF], response2_BIT
	jz		response2IsNotLoaded
	mov		a, 1
response2IsNotLoaded:
	ret

Isresponse3Loaded:
_Isresponse3Loaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+response3_ADDR_OFF], response3_BIT
	jz		response3IsNotLoaded
	mov		a, 1
response3IsNotLoaded:
	ret

Isresponse4Loaded:
_Isresponse4Loaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+response4_ADDR_OFF], response4_BIT
	jz		response4IsNotLoaded
	mov		a, 1
response4IsNotLoaded:
	ret

Isservo_transmitLoaded:
_Isservo_transmitLoaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+servo_transmit_ADDR_OFF], servo_transmit_BIT
	jz		servo_transmitIsNotLoaded
	mov		a, 1
servo_transmitIsNotLoaded:
	ret

